extra_sources = \
  custom-cursors,\
  render-state-helpers,\
  wideners/checkbox-widener-1.21,\
  wideners/scrollbar-texture-1.21.11,\
  wideners/selection-list-background-widener-1.21.11,\
  wideners/tooltip-widener

minecraft.version.major = 26.3

fabric.loom = plain

fabric.api.key_mapping_module = fabric-key-mapping-api-v1

preprocessor.mc_version_number = 260300
preprocessor.rendering = GUI_GRAPHICS_EXTRACTOR
preprocessor.checkbox_size = FONT
preprocessor.checkbox_change_handler =
preprocessor.editbox_cursor_to_start_param =
preprocessor.transparent_menus =
preprocessor.scroll_directions = BOTH
